package cn.intentforge.agent.core;

/**
 * One step in the coding plan generated by the planner stage.
 *
 * @param id stable step identifier
 * @param title short step title
 * @param description detailed step explanation
 * @param toolId optional recommended tool identifier
 * @param required whether the step is mandatory for completion
 */
public record PlanStep(
    String id,
    String title,
    String description,
    String toolId,
    boolean required
) {
  /**
   * Creates a validated plan step.
   */
  public PlanStep {
    id = AgentModelSupport.requireText(id, "id");
    title = AgentModelSupport.requireText(title, "title");
    description = AgentModelSupport.requireText(description, "description");
    toolId = AgentModelSupport.normalize(toolId);
  }
}
